'use client';
import {useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {useReviewTools} from '@/lib/use-review-tools';
import {Textarea} from '@/components/ui/textarea';
import {Upload,Download,Check,ArrowRight,FileText,ShieldCheck} from 'lucide-react';
import {parseCSV,exportCSV,finalRows,reviewRows,parseGlossary,type Row,type Issue,type Decision} from '@/lib/review.mjs';
export default function Home(){
 const [rows,setRows]=useState<Row[]>([]),[issues,setIssues]=useState<Issue[]>([]),[decisions,setDecisions]=useState<Record<string,Decision>>({}),[selected,setSelected]=useState(''),[glossary,setGlossary]=useState('工作区=workspace'),[context,setContext]=useState('面向个人和小团队的在线协作产品。语气简洁、清晰、友好。'),[message,setMessage]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[fileName,setFileName]=useState('未导入文案');
 const picker=useRef<HTMLInputElement>(null);const row=rows.find(r=>r.id===selected);const currentIssues=issues.filter(i=>i.id===selected);const accepted=Object.values(decisions).filter(d=>d.status==='accepted').length;const draft=row?(decisions[row.id]?.text??row.target):'';
 function load(text:string,name:string){const next=parseCSV(text);setRows(next);setSelected(next[0].id);setIssues([]);setDecisions({});setReviewed(false);setFileName(name);setMessage(`已导入 ${next.length} 条文案。`)}
 async function sample(){try{const r=await fetch('/ui-copy.csv');if(!r.ok)throw Error('示例加载失败。');load(await r.text(),'合成示例 · 10 条')}catch(e){setMessage(String(e))}}
 function review(){try{const result=reviewRows(finalRows(rows,decisions),parseGlossary(glossary));setIssues(result);setReviewed(true);setMessage(`规则检查完成，发现 ${result.length} 项待核对问题。语义与语气仍需人工审校。`)}catch(e){setMessage((e as Error).message)}}
 function decide(status:Decision['status']){if(!row)return;if(status==='accepted'&&!draft.trim()){setMessage('请先填写最终译文。');return}setDecisions(d=>({...d,[row.id]:{status,text:draft}}));setMessage(status==='accepted'?'修改已确认，导出将使用此译文。':status==='needs-context'?'已标记需要补充语境，导出将保留原译文。':'已保留原译文。')}
 function download(safe=false){const blob=new Blob(['\ufeff'+exportCSV(finalRows(rows,decisions),safe)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=safe?'localecheck-spreadsheet.csv':'localecheck-reviewed.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('已导出：仅已确认的条目使用修改后的译文。')}
 async function ai(){setBusy(true);setMessage('正在请求 AI 审校…');try{const res=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:finalRows(rows,decisions),context,glossary:parseGlossary(glossary)})});const data=await res.json() as {error?:string;issues:Issue[]};if(!res.ok)throw Error(data.error||'AI 审校失败，请重试。');setIssues(prev=>[...prev.filter(i=>i.origin!=='AI'),...data.issues]);setReviewed(true);setMessage('AI 审校完成。建议仅供核对，需逐条确认。')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 useReviewTools({load,read:()=>({rows,issues,decisions}),export:()=>exportCSV(finalRows(rows,decisions))});
 return <main className="workspace"><header><strong><span className="logo">LC</span> LocaleCheck</strong><small>中文 <ArrowRight size={14}/> English <span className="version">早期试用版</span></small></header>
 <section className="intro"><div><p className="eyebrow">LOCALIZATION / REVIEW</p><h1>每一句英文，都有据可查。</h1><p>先检查，再确认。为你的下一次产品上线做好准备。</p></div><div className="actions"><Button variant="outline" onClick={sample} disabled={busy}><FileText/>体验示例</Button><Button onClick={()=>picker.current?.click()} disabled={busy}><Upload/>导入 CSV</Button><input hidden ref={picker} type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1_000_000)throw Error('文件超过 1 MB 限制。');load(await file.text(),file.name)}catch(err){setMessage((err as Error).message)}e.target.value=''}}/></div></section>
 <div className="stats"><div><span>当前文案</span><strong>{rows.length.toString().padStart(2,'0')}</strong></div><div><span>待核对问题</span><strong>{issues.length.toString().padStart(2,'0')}</strong></div><div><span>已确认译文</span><strong>{accepted.toString().padStart(2,'0')}</strong></div><p><ShieldCheck size={20}/>修改由你决定<br/><small>刷新页面会清空当前工作，请及时导出。</small></p></div>
 <div className="workgrid"><aside className="config panel"><p className="eyebrow">01 / 审校设置</p><h2>给文案一点背景</h2><label htmlFor="context">产品与受众</label><Textarea id="context" value={context} onChange={e=>{setContext(e.target.value);setIssues([]);setReviewed(false);setMessage('产品背景已更改，请重新运行检查。')}} rows={4}/><label htmlFor="glossary">术语表</label><Textarea id="glossary" value={glossary} onChange={e=>{setGlossary(e.target.value);setIssues([]);setReviewed(false);setMessage('术语表已更改，请重新运行检查。')}} rows={5}/><small>每行一项，例如：工作区=workspace</small><Button onClick={review} disabled={!rows.length||busy}>运行规则检查 <ArrowRight/></Button><Button variant="outline" onClick={ai} disabled={!rows.length||busy}>{busy?'正在审校…':'AI 语义审校'}</Button><p className="note">规则检查覆盖数字、占位符、空译文和术语。AI 审校需先配置模型服务；点击后会发送当前文案、背景与术语表。修改审校设置后，旧结果会被清除。</p><a href="/ui-copy.csv" download>下载 CSV 模板 ↗</a></aside>
 <section className="panel queue"><div className="panelhead"><div><p className="eyebrow">02 / 文案队列</p><h2>{fileName}</h2></div><span className="pill">{reviewed?'检查已完成':'等待检查'}</span></div>{!rows.length?<div className="empty"><FileText size={36}/><h3>从一份文案表开始</h3><p>支持 id、source、target 和可选 context 列。<br/>最多 100 条，支持带引号的逗号和换行。</p><Button variant="outline" onClick={sample}>载入 10 条示例</Button></div>:<Table><TableHeader><TableRow><TableHead>中文 / English</TableHead><TableHead>审校状态</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id} data-state={selected===r.id?'selected':undefined}><TableCell><button className="rowbutton" onClick={()=>setSelected(r.id)}><small>{r.id}</small><b>{r.source}</b><span>{decisions[r.id]?.status==='accepted'?decisions[r.id].text:r.target||'（译文为空）'}</span></button></TableCell><TableCell><span className={'pill '+(issues.some(i=>i.id===r.id)?'warning':'')}>{decisions[r.id]?.status==='accepted'?'已确认':decisions[r.id]?.status==='rejected'?'保留原文':decisions[r.id]?.status==='needs-context'?'需要语境':issues.filter(i=>i.id===r.id).length?`${issues.filter(i=>i.id===r.id).length} 项问题`:reviewed?'未发现规则问题':'待检查'}</span></TableCell></TableRow>)}</TableBody></Table>}</section>
 <aside className="panel editor"><p className="eyebrow">03 / 人工确认</p>{row?<><h2>{row.source}</h2><p className="context">{row.context||'未提供使用位置；请结合实际界面核对。'}</p><p className="field-label">原译文</p><p className="original">{row.target||'（空）'}</p><div className="findings">{currentIssues.length?currentIssues.map((i,n)=><article key={n}><span className="pill warning">{i.origin} · {i.category}{i.severity?` · ${i.severity}风险`:''}</span><p>{i.reason}</p>{i.evidence&&<p><strong>依据：</strong>{i.evidence}</p>}{i.needsContext&&<p><strong>需要补充语境后再判断。</strong></p>}{i.model&&<small>{i.model} · Prompt {i.promptVersion}</small>}{i.suggestion&&<Button variant="outline" onClick={()=>setDecisions(d=>({...d,[row.id]:{status:'pending',text:i.suggestion}}))}>填入建议译文</Button>}</article>):<p className="note">{reviewed?'未发现规则问题不代表译文准确，请继续核对语义和语气。':'运行检查后，在这里查看问题依据。'}</p>}</div><label htmlFor="draft">最终译文</label><Textarea id="draft" value={draft} onChange={e=>setDecisions(d=>({...d,[row.id]:{status:'pending',text:e.target.value}}))} rows={4}/><div className="actions"><Button onClick={()=>decide('accepted')} disabled={busy}><Check/>确认修改</Button><Button variant="outline" onClick={()=>decide('rejected')} disabled={busy}>保留原译文</Button><Button variant="outline" onClick={()=>decide('needs-context')} disabled={busy}>需要补充语境</Button></div></>:<div className="empty"><p>选择一条文案，查看问题与修改。</p></div>}</aside></div>
 <footer><output aria-live="polite">{message||'文案默认只在当前页面处理。示例为合成数据。'}</output><div className="actions"><Button variant="outline" disabled={!rows.length||busy} onClick={()=>download(true)}>导出表格安全版</Button><Button disabled={!rows.length||busy} onClick={()=>download()}><Download/>导出 CSV</Button></div></footer><p className="footnote">标准 CSV 保留字段内容。表格安全版会给公式开头的字段加单引号，适合用电子表格打开。</p></main>
}
