export type Row={id:string;source:string;target:string;context:string};
export type Issue={id:string;category:string;reason:string;origin:string;suggestion:string;severity?:'高'|'中'|'低';evidence?:string;needsContext?:boolean;model?:string;promptVersion?:string};
export type Decision={status:'accepted'|'rejected'|'pending'|'needs-context';text:string};
export function decodeUTF8(input:ArrayBuffer|ArrayBufferView):string;
export function parseCSV(input:string):Row[];
export function exportCSV(rows:Row[],safe?:boolean):string;
export function finalRows(rows:Row[],decisions:Record<string,Decision>):Row[];
export function parseGlossary(text:string):{source:string;target:string}[];
export function reviewRows(rows:Row[],glossary?:{source:string;target:string}[]):Issue[];
